### ISSUE TITLE
Ball Image Problems

### ISSUE THREAD

**Issue by rafaelcandamil** [United-WeAre/Final-Project#2]
We are having trouble assingning the image itself to the ball code, during the class setup we keep encountering a NullPointerException, even though everything is being called in order.

**Comment by rafaelcandamil** [comment]
by the way the issue is in the last commit to ball class by andrew

**Comment by jgerstein** [comment]
Alright, your problems are pretty simple.

What it all boils down to is that you're using loadImage() outside of setup(){}.
- The first change I made was to not declare and initialize PImage Ball2 in the main tab at all - that's part of your class so you don't need it.
- The second change I made was to move the initialization of the Ball name b into setup(){}
- An excerpt of my changes is below:

``` java
boolean kickactivate1 = false;
boolean kickactivate2 = false;
//PImage Ball2 = loadImage("Ball2.jpg");
Ball b;
void setup() {
  size(800, 600);        //creates size of canvas
  rectMode(CENTER);
  //Ball2 = loadImage("Ball2.jpg");
  b = new Ball();
}
```

**Comment by rafaelcandamil** [comment]
THANK YOU SOOO MUCHHHHHH. that got it all working.
